### PR TITLE
Bug 1252088 - Ripple click effect needs more unit tests. r=Standard8

### PR DESCRIPTION
**Pull request by mancas**

### CODE REVIEW

**Comment by mancas** [comment]
We already have tests for the _onRemoteCursorPositionChange in conversation_test.js

**Comment by Standard8** [comment]
> We already have tests for the _onRemoteCursorPositionChange in conversation_test.js

Ah yes, I'd missed that.

Though I think we still need a test for `CursorClick` coming from the browser/LoopAPI similar to `#cursor position change`.

Can you also rebase on latest master so that travis passes please?

**Comment by mancas** [comment]
I think you mean this test: https://github.com/mancas/loop/blob/bug1252088/shared/test/remoteCursorStore_test.js#L70 right?

**Comment by Standard8** [comment]
> I think you mean this test: https://github.com/mancas/loop/blob/bug1252088/shared/test/remoteCursorStore_test.js#L70 right?

Yes, that's the one. Thanks for finding it!

**Pull request merged**
