### PR TITLE
No Bug. Fix the invitiation view on the ui-showcase.

### PR DESCRIPTION
**Pull request by Standard8**
The invitation view isn't showing the correct display on the ui-showcase at the moment. This is enough to fix it. r? @Mardak

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Mardak** [comment]
I see `Desktop room conversation (invitation, text-chat inclusion/scrollbars don't happen in real client)` working with this! r=Mardak

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request merged**
