### PR TITLE
No bug. Allow a branch to be specified when deploying to the standalone.

### PR DESCRIPTION
**Pull request by Standard8**
This allows us to specify which branch to use for the loop repo - which means its easier to set up loop-demo on akita.

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Mardak** [comment]
rs=Mardak (I'm assuming $BRANCH will probably be used with a git tag?)

**Comment by Standard8** [comment]
> rs=Mardak (I'm assuming $BRANCH will probably be used with a git tag?)

Its for the branch - so `master` or `akita`. This is the script for just auto deploying the standalone, not releasing it.

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request merged**
