### PR TITLE
Clean up Makefile to use a single shared babel recipe for building js files.

### PR DESCRIPTION
**Pull request by Mardak**
This would probably simplify #414 quite a bit. r?@dmose

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Mardak** [comment]
There was some discussion to get @Standard8's feedback given the original comment: `the idea is that it's better to keep the feel readable/maintainable by non Make-experts, even at the cost of some repetition.`

**Comment by Standard8** [comment]
> There was some discussion to get @Standard8's feedback given the original comment: `the idea is that it's better to keep the feel readable/maintainable by non Make-experts, even at the cost of some repetition.`

I'm fine with changing. I think its better to let this be tidied up a bit, rather than struggle on with limitations. The documentation in the patch helps understanding as well, even if people aren't too familiar with make.

**Comment by Standard8** [comment]
r=Standard8 with a comment added about the ordering of the PREREQ lines.

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request merged**
