### PR TITLE
No bug. Update urls for dev servers following server configuration changes.

### PR DESCRIPTION
**Pull request by Standard8**

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by dmose** [comment]
rs=dmose

**Comment by daveccrit** [comment]
r=dcritch

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request merged**
