### PR TITLE
Update CONTRIBUTING.md with the Definition of Done

### PR DESCRIPTION
**Pull request by dmose**
I've moved the "accessible" part of the DoD to "When Practical", since we haven't been making the content parts of the code accessible at the moment and clarified a few bits.

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by dmose** [comment]
Requesting review from anyone who would like to give it.  @Standard8?  @Mardak?

**Comment by Standard8** [comment]
r=Standard8

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request merged**
