### PR TITLE
Turn on already-passing rules and enable some with few fixes.

### PR DESCRIPTION
**Pull request by Mardak**
r?@Standard8

I've got the no-code-changed rule additions in the first commit. A bunch of separate commits to turn on individual rules after some fixes. I can squash the desired additional rules into a combined second commit and drop the others.

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Standard8** [comment]
Looks good, I think like you say, two commits would be best. r=Standard8

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request merged**
