### PR TITLE
Remove error message about favicon when the error is just not-found.

### PR DESCRIPTION
**Pull request by ianb**
An example site that emits this warning continuously is https://bugzilla.mozilla.org

### CODE REVIEW

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mozilla-autolander-deprecated** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Mardak** [comment]
Fyi, you pushed  Fix the profile creation documentation  7ac0b81 to master (so it's included on this PR).

**Comment by Standard8** [comment]
@ianb you could land this with r=Standard8 if you fix the branch the branch/patch to only land the MozLoopAPI.jsm changes and not the profile creation docs.

**Comment by ianb** [comment]
Fixed commit and merged in #70

**Pull request closed without merging**
