### PR TITLE
Bug 1231804 - In conversation window remove the gear button and put a…

### PR DESCRIPTION
**Pull request by mancas**
…udio/face mute buttons at the center

### CODE REVIEW

**Comment by Standard8** [comment]
Hi Manu, I was just looking at bug 1206611 and realised that you're removing the .room-context html items, but you're not removing the css. If you could make sure to remove the classes and check for string removals, that'd be great.

**Comment by mikedeboer** [comment]
crap-a-rooney! - I didn't realize it was this much code... I guess another thing to happily get rid of?

**Comment by mikedeboer** [comment]
OK, r=me, but you do need to fix the eslint error!

**Comment by Standard8** [comment]
@mancas, I fixed the eslint failures and rebased, and landed this for you in c6624313e0b5804f3cb71f317450fec994e70766

**Pull request closed without merging**
